// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NotatAppApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260307161503_AddLectureCourse")]
    partial class AddLectureCourse
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NotatAppApi.Models.LectureCourse", b =>
                {
                    b.Property<int>("LectureCourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LectureCourseId"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LectureCourseId");

                    b.ToTable("LectureCourses");
                });

            modelBuilder.Entity("NotatAppApi.Models.Sheet", b =>
                {
                    b.Property<int>("SheetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SheetId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("EditedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LectureCourseId")
                        .HasColumnType("integer");

                    b.Property<string>("NoteType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SheetId");

                    b.HasIndex("LectureCourseId");

                    b.ToTable("Sheets");
                });

            modelBuilder.Entity("NotatAppApi.Models.Sheet", b =>
                {
                    b.HasOne("NotatAppApi.Models.LectureCourse", "LectureCourse")
                        .WithMany("Sheets")
                        .HasForeignKey("LectureCourseId");

                    b.Navigation("LectureCourse");
                });

            modelBuilder.Entity("NotatAppApi.Models.LectureCourse", b =>
                {
                    b.Navigation("Sheets");
                });
#pragma warning restore 612, 618
        }
    }
}
